### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by settwi** [spaceinventor/csh#6]
Do you have published documentation for this library? We are using it for CubeSat development.

Thanks
William

**Comment by troelsjessen** [comment]
Nothing readily available, unfortunately, I suggest you take inspiration from the CSH repository which also rely on CSP. On top of that, feel free to ask questions :-)

**Comment by troelsjessen** [comment]
Hi,
Feel free to take a look at the attached manual.

/Troels

[CSH - CSP Shell Manual v2.0.pdf](https://github.com/spaceinventor/csh/files/12123107/CSH.-.CSP.Shell.Manual.v2.0.pdf)

**Comment by settwi** [comment]
Thank you!
